-- MySQL Script generated by MySQL Workbench
-- mer. 28 nov. 2018 17:18:28 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema conteurDigitalDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema conteurDigitalDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conteurDigitalDB` ;
USE `conteurDigitalDB` ;

-- -----------------------------------------------------
-- Table `conteurDigitalDB`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conteurDigitalDB`.`admin` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `password` VARCHAR(45) NULL,
  `avatar` VARCHAR(45) NULL,
  `user_right` ENUM('admin', 'user') NULL,
  `bio_title` VARCHAR(255) NULL,
  `bio_content` LONGTEXT NULL,
  `bio_picture` VARCHAR(45) NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conteurDigitalDB`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conteurDigitalDB`.`article` (
  `id_article` INT NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NULL,
  `update_date` DATETIME NULL,
  `title` VARCHAR(45) NULL,
  `content` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_520_ci' NULL,
  `blog_status` ENUM('writting_progress', 'published', 'archived') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL,
  `front_page_favorite` TINYINT NULL,
  PRIMARY KEY (`id_article`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conteurDigitalDB`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conteurDigitalDB`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NULL,
  `update_date` DATE NULL,
  `content` VARCHAR(45) NULL,
  `pseudo_anominous` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `admin_id_user` INT NOT NULL,
  `article_id_article` INT NOT NULL,
  PRIMARY KEY (`id_comment`, `admin_id_user`, `article_id_article`),
  CONSTRAINT `fk_comment_admin`
    FOREIGN KEY (`admin_id_user`)
    REFERENCES `conteurDigitalDB`.`admin` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_article1`
    FOREIGN KEY (`article_id_article`)
    REFERENCES `conteurDigitalDB`.`article` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_comment_admin_idx` ON `conteurDigitalDB`.`comment` (`admin_id_user` ASC);

CREATE INDEX `fk_comment_article1_idx` ON `conteurDigitalDB`.`comment` (`article_id_article` ASC);


-- -----------------------------------------------------
-- Table `conteurDigitalDB`.`admin_has_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conteurDigitalDB`.`admin_has_article` (
  `admin_id_user` INT NOT NULL,
  `article_id_article` INT NOT NULL,
  PRIMARY KEY (`admin_id_user`, `article_id_article`),
  CONSTRAINT `fk_admin_has_article_admin1`
    FOREIGN KEY (`admin_id_user`)
    REFERENCES `conteurDigitalDB`.`admin` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_admin_has_article_article1`
    FOREIGN KEY (`article_id_article`)
    REFERENCES `conteurDigitalDB`.`article` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_admin_has_article_article1_idx` ON `conteurDigitalDB`.`admin_has_article` (`article_id_article` ASC);

CREATE INDEX `fk_admin_has_article_admin1_idx` ON `conteurDigitalDB`.`admin_has_article` (`admin_id_user` ASC);


-- -----------------------------------------------------
-- Table `conteurDigitalDB`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conteurDigitalDB`.`media` (
  `id_media` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `path` VARCHAR(255) NULL,
  `type` ENUM('image', 'pdf', 'video') NULL,
  PRIMARY KEY (`id_media`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conteurDigitalDB`.`article_has_media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conteurDigitalDB`.`article_has_media` (
  `article_id_article` INT NOT NULL,
  `media_id_media` INT NOT NULL,
  PRIMARY KEY (`article_id_article`, `media_id_media`),
  CONSTRAINT `fk_article_has_media_article1`
    FOREIGN KEY (`article_id_article`)
    REFERENCES `conteurDigitalDB`.`article` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_has_media_media1`
    FOREIGN KEY (`media_id_media`)
    REFERENCES `conteurDigitalDB`.`media` (`id_media`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_article_has_media_media1_idx` ON `conteurDigitalDB`.`article_has_media` (`media_id_media` ASC);

CREATE INDEX `fk_article_has_media_article1_idx` ON `conteurDigitalDB`.`article_has_media` (`article_id_article` ASC);


-- -----------------------------------------------------
-- Table `conteurDigitalDB`.`credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conteurDigitalDB`.`credit` (
  `id_credit` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_credit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conteurDigitalDB`.`media_has_credit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conteurDigitalDB`.`media_has_credit` (
  `media_id_media` INT NOT NULL,
  `credit_id_credit` INT NOT NULL,
  PRIMARY KEY (`media_id_media`, `credit_id_credit`),
  CONSTRAINT `fk_media_has_credit_media1`
    FOREIGN KEY (`media_id_media`)
    REFERENCES `conteurDigitalDB`.`media` (`id_media`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_has_credit_credit1`
    FOREIGN KEY (`credit_id_credit`)
    REFERENCES `conteurDigitalDB`.`credit` (`id_credit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_media_has_credit_credit1_idx` ON `conteurDigitalDB`.`media_has_credit` (`credit_id_credit` ASC);

CREATE INDEX `fk_media_has_credit_media1_idx` ON `conteurDigitalDB`.`media_has_credit` (`media_id_media` ASC);


-- -----------------------------------------------------
-- Table `conteurDigitalDB`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conteurDigitalDB`.`tag` (
  `id_tag` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conteurDigitalDB`.`article_has_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conteurDigitalDB`.`article_has_tag` (
  `article_id_article` INT NOT NULL,
  `tag_id_tag` INT NOT NULL,
  PRIMARY KEY (`article_id_article`, `tag_id_tag`),
  CONSTRAINT `fk_article_has_tag_article1`
    FOREIGN KEY (`article_id_article`)
    REFERENCES `conteurDigitalDB`.`article` (`id_article`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_has_tag_tag1`
    FOREIGN KEY (`tag_id_tag`)
    REFERENCES `conteurDigitalDB`.`tag` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_article_has_tag_tag1_idx` ON `conteurDigitalDB`.`article_has_tag` (`tag_id_tag` ASC);

CREATE INDEX `fk_article_has_tag_article1_idx` ON `conteurDigitalDB`.`article_has_tag` (`article_id_article` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
